/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("nativewind/preset")],
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#d0dbed',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dee9fc',
        'surface-container-highest': '#d9e3f6',
        'on-surface': '#121c2a',
        'on-surface-variant': '#3e4947',
        'inverse-surface': '#27313f',
        'inverse-on-surface': '#eaf1ff',
        outline: '#6e7977',
        'outline-variant': '#bdc9c6',
        'surface-tint': '#006a63',
        primary: '#005c55',
        'on-primary': '#ffffff',
        'primary-container': '#0f766e',
        'on-primary-container': '#a3faef',
        'inverse-primary': '#80d5cb',
        secondary: '#3b665f',
        'on-secondary': '#ffffff',
        'secondary-container': '#bdece2',
        'on-secondary-container': '#416c65',
        tertiary: '#97253c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b73e53',
        'on-tertiary-container': '#ffe3e5',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#9cf2e8',
        'primary-fixed-dim': '#80d5cb',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#00504a',
        'secondary-fixed': '#bdece2',
        'secondary-fixed-dim': '#a2d0c6',
        'on-secondary-fixed': '#00201c',
        'on-secondary-fixed-variant': '#224e47',
        'tertiary-fixed': '#ffdadc',
        'tertiary-fixed-dim': '#ffb2b9',
        'on-tertiary-fixed': '#400010',
        'on-tertiary-fixed-variant': '#891933',
        background: '#f8f9ff',
        'on-background': '#121c2a',
        'surface-variant': '#d9e3f6'
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'metric-display': ['36px', { lineHeight: '40px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'metric-display-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'caption': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'micro-telemetry': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.25rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '3rem',
        'gutter-mobile': '1rem',
        'gutter-tablet': '1.5rem',
        'margin-mobile': '1rem',
        'margin-tablet': '2rem',
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
        '2xl': '20px',
        '3xl': '24px',
      }
    },
  },
  plugins: [],
}
